var data = [{ "id": 5,
    "cast": 
     [ "Tim Roth",
       "Antonio Banderas",
       "Jennifer Beals",
       "Madonna",
       "Marisa Tomei",
       "Bruce Willis",
       "Quentin Tarantino",
       "Salma Hayek",
       "Sammi Davis",
       "Amanda de Cadenet",
       "Valeria Golino",
       "Lili Taylor",
       "Patricia Vonne",
       "Lawrence Bender",
       "Ione Skye",
       "Alicia Witt",
       "David Proval",
       "Lana McKissack",
       "Tamlyn Tomita",
       "Kathy Griffin",
       "Danny Verduzco",
       "Paul Calderon",
       "Kimberly Blair",
       "Marc Lawrence" ] },
  { "id": 3,
    "cast": 
     [ "Matti Pellonpää",
       "Kati Outinen",
       "Sakari Kuosmanen",
       "Esko Nikkari",
       "Kylli Köngäs",
       "Pekka Laiho",
       "Jukka-Pekka Palo" ] },
  { "id": 2,
    "cast": 
     [ "Turo Pajala",
       "Susanna Haavisto",
       "Matti Pellonpää",
       "Eetu Hilkamo" ] },
  { "id": 6,
    "cast": 
     [ "Emilio Estevez",
       "Cuba Gooding Jr.",
       "Denis Leary",
       "Jeremy Piven",
       "Peter Greene",
       "Michael DeLorenzo",
       "Everlast",
       "Michael Wiseman",
       "Relioues Webb",
       "Eugene Williams",
       "Christine Harnos",
       "Galyn Görg",
       "Angela Alvarado",
       "Stephen Dorff",
       "Will Zahrn" ] },
  { "id": 8, "cast": [] },
  { "id": 9, "cast": [ "Rita Lengyel", "Milton Welsh" ] },
  { "id": 16,
    "cast": 
     [ "Björk",
       "Catherine Deneuve",
       "David Morse",
       "Peter Stormare",
       "Joel Grey",
       "Cara Seymour",
       "Vladica Kostic",
       "Jean-Marc Barr",
       "Vincent Paterson",
       "Siobhan Fallon",
       "Zeljko Ivanek",
       "Udo Kier",
       "Jens Albinus",
       "Reathel Bean",
       "Mette Berggreen",
       "Lars Michael Dinesen",
       "Katrine Falkenberg",
       "Michael Flessas",
       "John Randolph Jones",
       "Stellan Skarsgård",
       "Paprika Steen",
       "Noah Lazarus",
       "John Martinus",
       "Luke Reilly",
       "Sean-Michael Smith",
       "Al Agami",
       "Anna Norberg",
       "Troels Asmussen",
       "Caroline Sascha Cogez" ] },
  { "id": 19,
    "cast": 
     [ "Brigitte Helm",
       "Alfred Abel",
       "Gustav Fröhlich",
       "Rudolf Klein-Rogge",
       "Fritz Rasp",
       "Theodor Loos",
       "Erwin Biswanger",
       "Heinrich George",
       "Olaf Storm",
       "Hanns Leo Reich",
       "Helene Weigel",
       "Fritz Alberti",
       "Heinrich Gotho",
       "Margarete Lanner",
       "Grete Berger",
       "Georg John",
       "Curt Siodmak",
       "Rolf von Goth",
       "Helen von Münchofen",
       "Arthur Reinhardt",
       "Henrietta Siodmak" ] },
  { "id": 14,
    "cast": 
     [ "Kevin Spacey",
       "Annette Bening",
       "Thora Birch",
       "Wes Bentley",
       "Mena Suvari",
       "Chris Cooper",
       "Scott Bakula",
       "Peter Gallagher",
       "Allison Janney",
       "Sam Robards",
       "Barry Del Sherman",
       "John Cho",
       "Hal Fort Atkinson",
       "Kent Faulcon",
       "Ara Celi",
       "Sue Casey",
       "Brenda Wehle",
       "Lisa Cloud",
       "Amber Smith",
       "Joel McCrary",
       "Marissa Jaret Winokur",
       "Dennis Anderson",
       "Matthew Kimbrough",
       "Erin Cathryn Strubbe",
       "Alison Faulk",
       "Krista Goodsitt",
       "Lily Houtkin",
       "Carolina Lancaster",
       "Mona Leah",
       "Chekesha Van Putten",
       "Emily Zachary",
       "Nancy Anderson",
       "Reshma Gajjar",
       "Stephanie Rizzo",
       "Heather Joy Sher",
       "Chelsea Hertford",
       "Elaine Corral Kendall",
       "David C. Fisher",
       "Tom Miller",
       "Ronald Reagan",
       "Bruce Cohen" ] },
  { "id": 12,
    "cast": 
     [ "Albert Brooks",
       "Ellen DeGeneres",
       "Alexander Gould",
       "Willem Dafoe",
       "Brad Garrett",
       "Allison Janney",
       "Austin Pendleton",
       "Stephen Root",
       "Vicki Lewis",
       "Joe Ranft",
       "Geoffrey Rush",
       "John Ratzenberger",
       "Andrew Stanton",
       "Bob Peterson",
       "Barry Humphries",
       "Eric Bana",
       "Elizabeth Perkins",
       "Nicholas Bird",
       "Bill Hunter",
       "Bruce Spence",
       "LuLu Ebeling",
       "Jordan Ranft",
       "Erica Beck",
       "Erik Per Sullivan",
       "Rove McManus",
       "Carlos Alazraqui",
       "Phil Proctor",
       "Jim Ward",
       "Laura Marano",
       "Vanessa Marano",
       "Daryl Sabara",
       "Evan Sabara",
       "Jess Harnell",
       "Jan Rabson" ] },
  { "id": 13,
    "cast": 
     [ "Tom Hanks",
       "Robin Wright",
       "Gary Sinise",
       "Mykelti Williamson",
       "Sally Field",
       "Michael Conner Humphreys",
       "Hanna Hall",
       "Haley Joel Osment",
       "Siobhan Fallon",
       "Afemo Omilami",
       "Peter Dobson",
       "Sonny Shroyer",
       "George Kelly",
       "Sam Anderson",
       "Margo Moorer",
       "Christopher Jones",
       "Kevin Mangan",
       "Brett Rice",
       "Daniel C. Striepeke",
       "David Brisbin",
       "Kirk Ward",
       "Marlena Smalls",
       "Kitty K. Green",
       "Mark Matheisen",
       "Al Harrington",
       "Jed Gillin",
       "Don Fischer",
       "Matt Wallace",
       "Mike Jolly",
       "Michael Kemmerling",
       "John Voldstad",
       "Daniel J. Gillooly",
       "Michael Burgess",
       "Steven Griffith",
       "Michael McFall",
       "Michael McFall",
       "Byron Minns",
       "Stephen Bridgewater",
       "John William Galt",
       "Isabel Rose",
       "Richard D\"Alessandro",
       "Michael Jace",
       "Geoffrey Blake",
       "Vanessa Roth",
       "Dick Cavett",
       "Tiffany Salerno",
       "Tiffany Salerno",
       "Joe Alaskey",
       "Lazarus Jackson",
       "Lazarus Jackson",
       "Nora Dunfee",
       "Hallie D\"Amore",
       "Michael Mattison",
       "Charles Boswell",
       "Timothy McNeil",
       "Bob Penny",
       "Greg Brown",
       "Troy Christian",
       "Bryan Hanna",
       "Zach Hanner",
       "Aaron Michael Lacey",
       "Jacqueline Lovell",
       "Kurt Russell",
       "Brendan Shanahan",
       "William Shipman",
       "Robb Skyler",
       "Mary Ellen Trainor" ] },
  { "id": 17,
    "cast": 
     [ "Sean Bean",
       "Maria Bello",
       "Richard Elfyn",
       "Maurice Roeves",
       "Abigail Stone",
       "Sophie Stuckey",
       "Casper Harvey",
       "Eluned Jones",
       "Gwenyth Petty",
       "Robin Griffith" ] },
  { "id": 18,
    "cast": 
     [ "Bruce Willis",
       "Gary Oldman",
       "Ian Holm",
       "Milla Jovovich",
       "Chris Tucker",
       "Luke Perry",
       "Brion James",
       "Tommy \"Tiny\" Lister",
       "Lee Evans",
       "Charlie Creed-Miles",
       "Tricky",
       "John Neville",
       "John Bluthal",
       "Mathieu Kassovitz",
       "Christopher Fairbank",
       "Kim Chan",
       "Julie T. Wallace",
       "Al Matthews",
       "Maïwenn",
       "Mac McDonald",
       "Indra Ové",
       "Genevieve Maylam",
       "Jason Salkey",
       "Michael Culkin" ] },
  { "id": 11,
    "cast": 
     [ "Mark Hamill",
       "Harrison Ford",
       "Carrie Fisher",
       "Peter Cushing",
       "Alec Guinness",
       "Anthony Daniels",
       "Kenny Baker",
       "Peter Mayhew",
       "David Prowse",
       "James Earl Jones",
       "Phil Brown",
       "Shelagh Fraser",
       "Jack Purvis",
       "Eddie Byrne",
       "Denis Lawson",
       "Garrick Hagon",
       "Don Henderson",
       "Leslie Schofield",
       "Richard LeParmentier",
       "Michael Leader",
       "Alex McCrindle",
       "Drewe Henley",
       "Jack Klaff",
       "William Hootkins",
       "Angus MacInnes",
       "Jeremy Sinden",
       "Graham Ashley",
       "David Ankrum",
       "Mark Austin",
       "Scott Beach",
       "Lightning Bear",
       "Jon Berg",
       "Doug Beswick",
       "Paul Blake",
       "Janice Burchette",
       "Ted Burnett",
       "John Chapman",
       "Gilda Cohen",
       "Tim Condren",
       "Barry Copping",
       "Alfie Curtis",
       "Robert Davies",
       "Maria De Aragon",
       "Robert A. Denham",
       "Frazer Diamond",
       "Peter Diamond",
       "Warwick Diamond",
       "Sadie Eden",
       "Kim Falkinburg",
       "Harry Fielder",
       "Ted Gagliano",
       "Salo Gardner",
       "Steve Gawley",
       "Barry Gnome",
       "Rusty Goffe",
       "Isaac Grand",
       "Nelson Hall",
       "Reg Harding",
       "Alan Harris",
       "Frank Henson",
       "Christine Hewett",
       "Arthur Howell",
       "Tommy Ilsley",
       "Joe Johnston",
       "Annette Jones",
       "Linda Jones",
       "Joe Kaye",
       "Colin Michael Kitchens",
       "Melissa Kurtz",
       "Tiffany L. Kurtz",
       "Al Lampert",
       "Anthony Lang",
       "Laine Liska",
       "Derek Lyons",
       "Mahjoub",
       "Alf Mangan",
       "Rick McCallum",
       "Grant McCune",
       "Geoffrey Moon",
       "Mandy Morton",
       "Lorne Peterson",
       "Marcus Powell",
       "Shane Rimmer",
       "Pam Rose",
       "George Roubicek",
       "Erica Simmons",
       "Angela Staines",
       "George Stock",
       "Roy Straite",
       "Peter Sturgeon",
       "Peter Sumner",
       "John Sylla",
       "Tom Sylla",
       "Malcolm Tierney",
       "Phil Tippett",
       "Burnell Tucker",
       "Morgan Upton",
       "Jerry Walter",
       "Hal Wamsley",
       "Larry Ward",
       "Diana Sadley Way",
       "Harold Weed",
       "Bill Weston",
       "Steve \"Spaz\" Williams",
       "Fred Wood",
       "Colin Higgins" ] },
  { "id": 15,
    "cast": 
     [ "Orson Welles",
       "Joseph Cotten",
       "Dorothy Comingore",
       "Ray Collins",
       "George Coulouris",
       "Agnes Moorehead",
       "Paul Stewart",
       "Ruth Warrick",
       "Erskine Sanford",
       "William Alland",
       "Everett Sloane",
       "Fortunio Bonanova",
       "Gus Schilling",
       "Philip Van Zandt",
       "Georgia Backus",
       "Harry Shannon",
       "Sonny Bupp",
       "Buddy Swan",
       "Charles Bennett",
       "Gregg Toland",
       "Don Ackerman",
       "Nat \"King\" Cole",
       "Gino Corrado",
       "Maurice Costello",
       "Demetrius Alexis",
       "Gene Coogan",
       "Art Dupuis",
       "Rudy Germane",
       "Mike Lally",
       "Walter Lawrence",
       "John Northpole",
       "Victor Romito",
       "Bob Terry",
       "William Alston",
       "Jack Gargan",
       "Bert Moorhouse",
       "Carmen Laroux",
       "Sam Ash",
       "Buddy Messinger",
       "Terrance Ray",
       "Sally Corner",
       "Walter Bacon",
       "Herbert Corthell",
       "Harry A. Bailey",
       "Danny Borzage",
       "J.J. Clark",
       "Tom Coleman",
       "Carl Deloro",
       "Jack Egan",
       "Robert Haines",
       "Ludwig Lowry",
       "John McCormack",
       "Hercules Mendez",
       "Paddy O\"Flynn",
       "Sam Rice",
       "Don Roberts",
       "Larry Wheat",
       "Larry Williams",
       "Joan Blair",
       "Morgan Brown",
       "Harry Burkhardt",
       "Edmund Cobb",
       "Eddie Coke",
       "Louis Natheaux",
       "Arthur O\"Connell",
       "Guy Repp",
       "Tom Steele",
       "Richard Wilson",
       "Louise Currie",
       "Walter Sande",
       "Jan Wiley",
       "Milton Kibbee",
       "Buck Mack",
       "Alan Ladd",
       "Thomas A. Curran",
       "Jack Curtis",
       "George Noisom",
       "Gerald Pierce",
       "Donna Dax",
       "George DeNormand",
       "Bud Geary",
       "Bert LeBaron",
       "Clyde McAtee",
       "Cyril Ring",
       "Roland Winters",
       "Lew Harvey",
       "Herman J. Mankiewicz",
       "Eddie Dew",
       "Perc Launders",
       "John Dilson",
       "Walter James",
       "Robert Dudley",
       "Suzanne Dulier",
       "Al Eben",
       "Johnny Eckert",
       "Carl Ekberg",
       "Edith Evanson",
       "Carl Faulkner",
       "Juanita Fields",
       "Edna Mae Jones",
       "Leda Nicova",
       "Jolane Reynolds",
       "Suzanne Ridgeway",
       "Olin Francis",
       "Louise Franklin",
       "Renee Godfrey",
       "Peter Gowland",
       "Jimmy Grant",
       "Jesse Graves",
       "Ernest Grooney",
       "Jack Gwynne",
       "Teddy Mangean",
       "Henry Hebert",
       "Bryan \"Slim\" Hightower",
       "Mitchell Ingraham",
       "Philip Morris",
       "Francis Sayles",
       "George W. Jimenez",
       "Arthur Kay",
       "Ellen Lowe",
       "James T. Mack",
       "Mickey Martin",
       "Bruce Sidney",
       "Major McBride",
       "Frank McLure",
       "Charles Meakin",
       "Edward Peil Jr.",
       "Irving Mitchell",
       "Frances E. Neal",
       "Lillian Nicholson",
       "Joseph North",
       "William H. O\"Brien",
       "Field Norton",
       "Dick Scott",
       "Frank O\"Connor",
       "Russ Powell",
       "Bert Stevens",
       "Thomas Pogue",
       "Lillian O\"Malley",
       "Jack Raymond",
       "Gohr Van Vleck",
       "Myrtle Rishell",
       "Benny Rubin",
       "Shimen Ruskin",
       "George Sherwood",
       "Edward Ryan",
       "Landers Stevens",
       "Harry J. Vejar",
       "Tudor Williams",
       "Arthur Yeoman",
       "Tim Davis" ] } ,
       { "id": 25,
    "cast": 
     [ "Jamie Foxx",
       "Jake Gyllenhaal",
       "Scott MacDonald",
       "Lucas Black",
       "Peter Sarsgaard",
       "Laz Alonso",
       "Chris Cooper",
       "Brian Geraghty",
       "Damion Poitier",
       "John Krasinski",
       "Jocko Sims",
       "Kevin Foster",
       "Riad Galayini",
       "Craig Coyne",
       "Katherine Randolph",
       "Honorine Bell",
       "Dendrie Taylor",
       "James Morrison",
       "Ming Lo",
       "Dennis Haysbert" ] },
  { "id": 21,
    "cast": 
     [ "Michael Hynson",
       "Robert August",
       "Lord \"Tally Ho\" Blears",
       "Bruce Brown",
       "Chip Fitzwater",
       "Chuck Gardner",
       "Wayne Miyata" ] },
  { "id": 22,
    "cast": 
     [ "Johnny Depp",
       "Geoffrey Rush",
       "Orlando Bloom",
       "Keira Knightley",
       "Jack Davenport",
       "Jonathan Pryce",
       "Kevin McNally",
       "Zoe Saldana",
       "Lee Arenberg",
       "Mackenzie Crook",
       "Damian O\"Hare",
       "Giles New",
       "Angus Barnett",
       "David Bailie",
       "Martin Klebba",
       "Treva Etienne",
       "Michael Berry Jr.",
       "Isaac C. Singleton Jr.",
       "Greg Ellis",
       "Guy Siner",
       "Ralph P. Martin",
       "Paula J. Newman",
       "Paul Keith",
       "Dylan Smith",
       "Lucinda Dryzek",
       "Lauren Maher",
       "Vanessa Branch",
       "Luke de Woolfson",
       "Michael Sean Tighe",
       "Dustin Seavey",
       "Christian Martin",
       "Trevor Goddard",
       "Vince Lozano",
       "Matthew Bowyer",
       "Brye Cooper",
       "Ben Wilson",
       "Antonio Valentino",
       "Mike Babcock",
       "Owen Finnegan",
       "Ian McIntyre",
       "Israel Aduramo",
       "Sam Roberts",
       "Ben Roberts",
       "Félix Castro",
       "Mike Haberecht",
       "Rudolph McCollum",
       "Gerard J. Reyes",
       "M. Scott Shields",
       "Christopher Sullivan",
       "Craig Thomson",
       "Fred Toft",
       "Jerry Gauny",
       "Maxie J. Santillan Jr.",
       "Michael Earl Lane",
       "David Patykewich",
       "Tommy Schooler",
       "Finneus Egan",
       "D.P. FitzGerald",
       "Tobias McKinney",
       "Michael A. Thompson",
       "Michael W. Williams",
       "Jose Zelaya",
       "Don LaDaga",
       "LeJon",
       "Christopher S. Capp",
       "Gregory Alosio",
       "Jordi Caballero",
       "Paul Gagné",
       "Joe Grisaffi",
       "James McAuley" ] },
  { "id": 24,
    "cast": 
     [ "Uma Thurman",
       "Lucy Liu",
       "Vivica A. Fox",
       "Daryl Hannah",
       "David Carradine",
       "Michael Madsen",
       "Julie Dreyfus",
       "Chiaki Kuriyama",
       "Sonny Chiba",
       "Gordon Liu Chia-Hui",
       "Michael Parks",
       "Michael Bowen",
       "Jun Kunimura",
       "Kenji Ohba",
       "Yuki Kazamatsuri",
       "James Parks",
       "Sakichi Satô",
       "Jonathan Loughran",
       "Yoshiyuki Morishita",
       "Tetsuro Shimaguchi",
       "Kazuki Kitamura",
       "Yôji Tanaka",
       "Issei Takahashi",
       "Sô Yamanaka",
       "Julie Manase",
       "Akaji Maro",
       "Goro Daimon",
       "Shun Sugata",
       "Zhang Jin Zhan",
       "Hu Xiaohui",
       "Ambrosia Kelley",
       "Sachiko Fujii",
       "Shu Lan Tuan",
       "Ai Maeda",
       "Naomi Kusumi",
       "Hikaru Midorikawa" ] },
  { "id": 32,
    "cast": 
     [ "Hisao Egawa",
       "Nobuaki Fukuda",
       "Yu Hayashi",
       "Hiroaki Ishikawa",
       "Yoshio Kawai",
       "Takurô Kitagawa",
       "Atsuko Mine",
       "Takashi Nagasako",
       "Ryûji Nakagi",
       "Hidetoshi Nakamura",
       "Youko Otomo",
       "Ai Satô",
       "Masaharu Satô",
       "Kôzô Shioya",
       "Keiichi Sonobe",
       "Katsumi Suzuki",
       "Kazumi Tanaka",
       "Seiko Tomoe",
       "Keaton Yamada",
       "Keiko Yamamoto" ] },
  { "id": 26,
    "cast": 
     [ "Lior Ashkenazi",
       "Knut Berger",
       "Caroline Peters",
       "Gideon Shemer",
       "Carola Regnier",
       "Hanns Zischler",
       "Ernest Lenart" ] },
  { "id": 27,
    "cast": 
     [ "Kieran O\"Brien",
       "Margo Stilley",
       "Courtney Taylor-Taylor",
       "Alex Kapranos",
       "Guy Garvey",
       "Robert Levon Been",
       "Peter Hayes",
       "Gruff Rhys",
       "Jason Stollsteimer",
       "Marcie Bolen",
       "Michael Nyman",
       "Bobby Gillespie" ] },
  { "id": 31, "cast": [] },
  { "id": 35,
    "cast": 
     [ "Dan Castellaneta",
       "Julie Kavner",
       "Nancy Cartwright",
       "Yeardley Smith",
       "Hank Azaria",
       "Harry Shearer",
       "Kelsey Grammer",
       "Maile Flanagan",
       "Pamela Hayden",
       "Marcia Wallace",
       "Joe Mantegna",
       "Tom Hanks",
       "Billie Joe Armstrong",
       "Mike Dirnt",
       "Tre Cool",
       "Tress MacNeille",
       "Albert Brooks",
       "Russi Taylor",
       "Karl Wiedergott",
       "Maggie Roswell",
       "Philip Rosenthal" ] },
  { "id": 38,
    "cast": 
     [ "Jim Carrey",
       "Kate Winslet",
       "Elijah Wood",
       "Mark Ruffalo",
       "Kirsten Dunst",
       "Tom Wilkinson",
       "Ryan Whitney",
       "Jane Adams",
       "Debbon Ayer",
       "David Cross",
       "Gerry Robert Byrne",
       "Brian Price",
       "Josh Flitter",
       "Paul Litowsky",
       "Lola Daehler",
       "Amir Ali Said",
       "Deirdre O\"Connell",
       "Lauren Adler" ] },
  { "id": 30,
    "cast": 
     [ "Tsutomu Isobe",
       "Ami Hasegawa",
       "Gara Takashima",
       "Kouichi Yamadera" ] },
  { "id": 33,
    "cast": 
     [ "Clint Eastwood",
       "Gene Hackman",
       "Morgan Freeman",
       "Richard Harris",
       "Jaimz Woolvett",
       "Anna Levine",
       "Saul Rubinek",
       "Frances Fisher",
       "David Mucci",
       "Rob Campbell",
       "Anthony James",
       "Ron White",
       "Jefferson Mappin",
       "Jeremy Ratchford",
       "Philip Maurice Hayes",
       "Tara Frederick",
       "Beverley Elliott",
       "Liisa Repo-Martell",
       "Shane Meier",
       "Robert Koons",
       "Mina E. Mina",
       "John Pyper-Ferguson",
       "Walter Marsh",
       "Larry Reese",
       "Blair Haynes",
       "Frank C. Turner",
       "Lochlyn Munro",
       "Ben Cardinal",
       "Michael Charrois",
       "Michael Maurer",
       "Larry Joshua",
       "George Orrison",
       "Greg Goossen" ] },
  { "id": 28,
    "cast": 
     [ "Martin Sheen",
       "Marlon Brando",
       "Robert Duvall",
       "Laurence Fishburne",
       "Sam Bottoms",
       "Frederic Forrest",
       "Albert Hall",
       "Harrison Ford",
       "Dennis Hopper",
       "G. D. Spradlin",
       "Jerry Ziesmer",
       "Tom Mason",
       "Scott Glenn",
       "James Keane",
       "Kerry Rossall",
       "Colleen Camp",
       "Cynthia Wood",
       "Linda Carpenter",
       "Jack Thibeau",
       "Damien Leake",
       "Marc Coppola",
       "Glenn Walken",
       "Bill Graham",
       "Jerry Ross",
       "Charles Robinson",
       "Nick Nicholson",
       "Don Gordon Bell",
       "Evan A. Lottman",
       "R. Lee Ermey",
       "Jim Gaines",
       "Charlie Sheen",
       "Vittorio Storaro",
       "Francis Ford Coppola",
       "Henry Strzalkowski",
       "Lonnie Woodley" ] },
    { "id": 58,
        "cast": 
         [ "Johnny Depp",
           "Orlando Bloom",
           "Keira Knightley",
           "Bill Nighy",
           "Jack Davenport",
           "Stellan Skarsgård",
           "Kevin McNally",
           "Jonathan Pryce",
           "Lee Arenberg",
           "Mackenzie Crook",
           "Tom Hollander",
           "Naomie Harris",
           "David Bailie",
           "Martin Klebba",
           "David Schofield",
           "Alex Norton",
           "Geoffrey Rush",
           "Lauren Maher",
           "Vanessa Branch",
           "Luke de Woolfson",
           "Jonathan Kite",
           "Ho-Kwan Tse",
           "Peter Donald Badalamenti II",
           "Christopher S. Capp",
           "Max Baker",
           "Steve Speirs",
           "Reggie Lee" ] },
      { "id": 55,
        "cast": 
         [ "Gael García Bernal",
           "Vanessa Bauche",
           "Goya Toledo",
           "Alvaro Guerrero",
           "Emilio Echevarría",
           "Jorge Salinas",
           "Rodrigo Murray",
           "Humberto Busto",
           "Gerardo Campbell",
           "Rosa María Bianchi",
           "Dunia Saldívar",
           "Adriana Barraza",
           "José Sefami",
           "Lourdes Echevarría",
           "Marco Pérez",
           "Laura Almela",
           "Gustavo Sánchez Parra",
           "Dagoberto Gama",
           "Rodrigo Ostap",
           "Patricio Castillo",
           "Roberto Medina",
           "Carlos Samperio",
           "Mauricio Martínez",
           "Ricardo Dalmacci",
           "Gustavo Muñoz" ] },
      { "id": 59,
        "cast": 
         [ "Viggo Mortensen",
           "Maria Bello",
           "Heidi Hayes",
           "Ashton Holmes",
           "William Hurt",
           "Ed Harris",
           "Peter MacNeill",
           "Stephen McHattie",
           "Greg Bryk",
           "Kyle Schmid",
           "Sumela Kay",
           "Gerry Quigley",
           "Deborah Drakeford",
           "Bill MacDonald",
           "Aidan Devine" ] } ]

var people = [
            { "name": "Tim Roth", "group": 1 },
            { "name": "Antonio Banderas", "group": 1 },
            { "name": "Jennifer Beals", "group": 1 },
            { "name": "Madonna", "group": 1 },
            { "name": "Marisa Tomei", "group": 1 },
            { "name": "Bruce Willis", "group": 1 },
            { "name": "Quentin Tarantino", "group": 1 },
            { "name": "Salma Hayek", "group": 1 },
            { "name": "Sammi Davis", "group": 1 },
            { "name": "Amanda de Cadenet", "group": 1 },
            { "name": "Valeria Golino", "group": 1 },
            { "name": "Lili Taylor", "group": 1 },
            { "name": "Patricia Vonne", "group": 1 },
            { "name": "Lawrence Bender", "group": 1 },
            { "name": "Ione Skye", "group": 1 },
            { "name": "Alicia Witt", "group": 1 },
            { "name": "David Proval", "group": 1 },
            { "name": "Lana McKissack", "group": 1 },
            { "name": "Tamlyn Tomita", "group": 1 },
            { "name": "Kathy Griffin", "group": 1 },
            { "name": "Danny Verduzco", "group": 1 },
            { "name": "Paul Calderon", "group": 1 },
            { "name": "Kimberly Blair", "group": 1 },
            { "name": "Marc Lawrence", "group": 1 },
            { "name": "Matti Pellonpää", "group": 1 },
            { "name": "Kati Outinen", "group": 1 },
            { "name": "Sakari Kuosmanen", "group": 1 },
            { "name": "Esko Nikkari", "group": 1 },
            { "name": "Kylli Köngäs", "group": 1 },
            { "name": "Pekka Laiho", "group": 1 },
            { "name": "Jukka-Pekka Palo", "group": 1 },
            { "name": "Turo Pajala", "group": 1 },
            { "name": "Susanna Haavisto", "group": 1 },
            { "name": "Matti Pellonpää", "group": 1 },
            { "name": "Eetu Hilkamo", "group": 1 },
            { "name": "Emilio Estevez", "group": 1 },
            { "name": "Cuba Gooding Jr.", "group": 1 },
            { "name": "Denis Leary", "group": 1 },
            { "name": "Jeremy Piven", "group": 1 },
            { "name": "Peter Greene", "group": 1 },
            { "name": "Michael DeLorenzo", "group": 1 },
            { "name": "Everlast", "group": 1 },
            { "name": "Michael Wiseman", "group": 1 },
            { "name": "Relioues Webb", "group": 1 },
            { "name": "Eugene Williams", "group": 1 },
            { "name": "Christine Harnos", "group": 1 },
            { "name": "Galyn Görg", "group": 1 },
            { "name": "Angela Alvarado", "group": 1 },
            { "name": "Stephen Dorff", "group": 1 },
            { "name": "Will Zahrn", "group": 1 },
            { "name": "Rita Lengyel", "group": 1 },
            { "name": "Milton Welsh", "group": 1 },
            { "name": "Björk", "group": 1 },
            { "name": "Catherine Deneuve", "group": 1 },
            { "name": "David Morse", "group": 1 },
            { "name": "Peter Stormare", "group": 1 },
            { "name": "Joel Grey", "group": 1 },
            { "name": "Cara Seymour", "group": 1 },
            { "name": "Vladica Kostic", "group": 1 },
            { "name": "Jean-Marc Barr", "group": 1 },
            { "name": "Vincent Paterson", "group": 1 },
            { "name": "Siobhan Fallon", "group": 1 },
            { "name": "Zeljko Ivanek", "group": 1 },
            { "name": "Udo Kier", "group": 1 },
            { "name": "Jens Albinus", "group": 1 },
            { "name": "Reathel Bean", "group": 1 },
            { "name": "Mette Berggreen", "group": 1 },
            { "name": "Lars Michael Dinesen", "group": 1 },
            { "name": "Katrine Falkenberg", "group": 1 },
            { "name": "Michael Flessas", "group": 1 },
            { "name": "John Randolph Jones", "group": 1 },
            { "name": "Stellan Skarsgård", "group": 1 },
            { "name": "Paprika Steen", "group": 1 },
            { "name": "Noah Lazarus", "group": 1 },
            { "name": "John Martinus", "group": 1 },
            { "name": "Luke Reilly", "group": 1 },
            { "name": "Sean-Michael Smith", "group": 1 },
            { "name": "Al Agami", "group": 1 },
            { "name": "Anna Norberg", "group": 1 },
            { "name": "Troels Asmussen", "group": 1 },
            { "name": "Caroline Sascha Cogez", "group": 1 },
            { "name": "Brigitte Helm", "group": 1 },
            { "name": "Alfred Abel", "group": 1 },
            { "name": "Gustav Fröhlich", "group": 1 },
            { "name": "Rudolf Klein-Rogge", "group": 1 },
            { "name": "Fritz Rasp", "group": 1 },
            { "name": "Theodor Loos", "group": 1 },
            { "name": "Erwin Biswanger", "group": 1 },
            { "name": "Heinrich George", "group": 1 },
            { "name": "Olaf Storm", "group": 1 },
            { "name": "Hanns Leo Reich", "group": 1 },
            { "name": "Helene Weigel", "group": 1 },
            { "name": "Fritz Alberti", "group": 1 },
            { "name": "Heinrich Gotho", "group": 1 },
            { "name": "Margarete Lanner", "group": 1 },
            { "name": "Grete Berger", "group": 1 },
            { "name": "Georg John", "group": 1 },
            { "name": "Curt Siodmak", "group": 1 },
            { "name": "Rolf von Goth", "group": 1 },
            { "name": "Helen von Münchofen", "group": 1 },
            { "name": "Arthur Reinhardt", "group": 1 },
            { "name": "Henrietta Siodmak", "group": 1 },
            { "name": "Kevin Spacey", "group": 1 },
            { "name": "Annette Bening", "group": 1 },
            { "name": "Thora Birch", "group": 1 },
            { "name": "Wes Bentley", "group": 1 },
            { "name": "Mena Suvari", "group": 1 },
            { "name": "Chris Cooper", "group": 1 },
            { "name": "Scott Bakula", "group": 1 },
            { "name": "Peter Gallagher", "group": 1 },
            { "name": "Allison Janney", "group": 1 },
            { "name": "Sam Robards", "group": 1 },
            { "name": "Barry Del Sherman", "group": 1 },
            { "name": "John Cho", "group": 1 },
            { "name": "Hal Fort Atkinson", "group": 1 },
            { "name": "Kent Faulcon", "group": 1 },
            { "name": "Ara Celi", "group": 1 },
            { "name": "Sue Casey", "group": 1 },
            { "name": "Brenda Wehle", "group": 1 },
            { "name": "Lisa Cloud", "group": 1 },
            { "name": "Amber Smith", "group": 1 },
            { "name": "Joel McCrary", "group": 1 },
            { "name": "Marissa Jaret Winokur", "group": 1 },
            { "name": "Dennis Anderson", "group": 1 },
            { "name": "Matthew Kimbrough", "group": 1 },
            { "name": "Erin Cathryn Strubbe", "group": 1 },
            { "name": "Alison Faulk", "group": 1 },
            { "name": "Krista Goodsitt", "group": 1 },
            { "name": "Lily Houtkin", "group": 1 },
            { "name": "Carolina Lancaster", "group": 1 },
            { "name": "Mona Leah", "group": 1 },
            { "name": "Chekesha Van Putten", "group": 1 },
            { "name": "Emily Zachary", "group": 1 },
            { "name": "Nancy Anderson", "group": 1 },
            { "name": "Reshma Gajjar", "group": 1 },
            { "name": "Stephanie Rizzo", "group": 1 },
            { "name": "Heather Joy Sher", "group": 1 },
            { "name": "Chelsea Hertford", "group": 1 },
            { "name": "Elaine Corral Kendall", "group": 1 },
            { "name": "David C. Fisher", "group": 1 },
            { "name": "Tom Miller", "group": 1 },
            { "name": "Ronald Reagan", "group": 1 },
            { "name": "Bruce Cohen", "group": 1 },
            { "name": "Albert Brooks", "group": 1 },
            { "name": "Ellen DeGeneres", "group": 1 },
            { "name": "Alexander Gould", "group": 1 },
            { "name": "Willem Dafoe", "group": 1 },
            { "name": "Brad Garrett", "group": 1 },
            { "name": "Allison Janney", "group": 1 },
            { "name": "Austin Pendleton", "group": 1 },
            { "name": "Stephen Root", "group": 1 },
            { "name": "Vicki Lewis", "group": 1 },
            { "name": "Joe Ranft", "group": 1 },
            { "name": "Geoffrey Rush", "group": 1 },
            { "name": "John Ratzenberger", "group": 1 },
            { "name": "Andrew Stanton", "group": 1 },
            { "name": "Bob Peterson", "group": 1 },
            { "name": "Barry Humphries", "group": 1 },
            { "name": "Eric Bana", "group": 1 },
            { "name": "Elizabeth Perkins", "group": 1 },
            { "name": "Nicholas Bird", "group": 1 },
            { "name": "Bill Hunter", "group": 1 },
            { "name": "Bruce Spence", "group": 1 },
            { "name": "LuLu Ebeling", "group": 1 },
            { "name": "Jordan Ranft", "group": 1 },
            { "name": "Erica Beck", "group": 1 },
            { "name": "Erik Per Sullivan", "group": 1 },
            { "name": "Rove McManus", "group": 1 },
            { "name": "Carlos Alazraqui", "group": 1 },
            { "name": "Phil Proctor", "group": 1 },
            { "name": "Jim Ward", "group": 1 },
            { "name": "Laura Marano", "group": 1 },
            { "name": "Vanessa Marano", "group": 1 },
            { "name": "Daryl Sabara", "group": 1 },
            { "name": "Evan Sabara", "group": 1 },
            { "name": "Jess Harnell", "group": 1 },
            { "name": "Jan Rabson", "group": 1 },
            { "name": "Tom Hanks", "group": 1 },
            { "name": "Robin Wright", "group": 1 },
            { "name": "Gary Sinise", "group": 1 },
            { "name": "Mykelti Williamson", "group": 1 },
            { "name": "Sally Field", "group": 1 },
            { "name": "Michael Conner Humphreys", "group": 1 },
            { "name": "Hanna Hall", "group": 1 },
            { "name": "Haley Joel Osment", "group": 1 },
            { "name": "Siobhan Fallon", "group": 1 },
            { "name": "Afemo Omilami", "group": 1 },
            { "name": "Peter Dobson", "group": 1 },
            { "name": "Sonny Shroyer", "group": 1 },
            { "name": "George Kelly", "group": 1 },
            { "name": "Sam Anderson", "group": 1 },
            { "name": "Margo Moorer", "group": 1 },
            { "name": "Christopher Jones", "group": 1 },
            { "name": "Kevin Mangan", "group": 1 },
            { "name": "Brett Rice", "group": 1 },
            { "name": "Daniel C. Striepeke", "group": 1 },
            { "name": "David Brisbin", "group": 1 },
            { "name": "Kirk Ward", "group": 1 },
            { "name": "Marlena Smalls", "group": 1 },
            { "name": "Kitty K. Green", "group": 1 },
            { "name": "Mark Matheisen", "group": 1 },
            { "name": "Al Harrington", "group": 1 },
            { "name": "Jed Gillin", "group": 1 },
            { "name": "Don Fischer", "group": 1 },
            { "name": "Matt Wallace", "group": 1 },
            { "name": "Mike Jolly", "group": 1 },
            { "name": "Michael Kemmerling", "group": 1 },
            { "name": "John Voldstad", "group": 1 },
            { "name": "Daniel J. Gillooly", "group": 1 },
            { "name": "Michael Burgess", "group": 1 },
            { "name": "Steven Griffith", "group": 1 },
            { "name": "Michael McFall", "group": 1 },
            { "name": "Michael McFall", "group": 1 },
            { "name": "Byron Minns", "group": 1 },
            { "name": "Stephen Bridgewater", "group": 1 },
            { "name": "John William Galt", "group": 1 },
            { "name": "Isabel Rose", "group": 1 },
            { "name": "Richard D'Alessandro", "group": 1 },
            { "name": "Michael Jace", "group": 1 },
            { "name": "Geoffrey Blake", "group": 1 },
            { "name": "Vanessa Roth", "group": 1 },
            { "name": "Dick Cavett", "group": 1 },
            { "name": "Tiffany Salerno", "group": 1 },
            { "name": "Tiffany Salerno", "group": 1 },
            { "name": "Joe Alaskey", "group": 1 },
            { "name": "Lazarus Jackson", "group": 1 },
            { "name": "Lazarus Jackson", "group": 1 },
            { "name": "Nora Dunfee", "group": 1 },
            { "name": "Hallie D'Amore", "group": 1 },
            { "name": "Michael Mattison", "group": 1 },
            { "name": "Charles Boswell", "group": 1 },
            { "name": "Timothy McNeil", "group": 1 },
            { "name": "Bob Penny", "group": 1 },
            { "name": "Greg Brown", "group": 1 },
            { "name": "Troy Christian", "group": 1 },
            { "name": "Bryan Hanna", "group": 1 },
            { "name": "Zach Hanner", "group": 1 },
            { "name": "Aaron Michael Lacey", "group": 1 },
            { "name": "Jacqueline Lovell", "group": 1 },
            { "name": "Kurt Russell", "group": 1 },
            { "name": "Brendan Shanahan", "group": 1 },
            { "name": "William Shipman", "group": 1 },
            { "name": "Robb Skyler", "group": 1 },
            { "name": "Mary Ellen Trainor", "group": 1 },
            { "name": "Sean Bean", "group": 1 },
            { "name": "Maria Bello", "group": 1 },
            { "name": "Richard Elfyn", "group": 1 },
            { "name": "Maurice Roeves", "group": 1 },
            { "name": "Abigail Stone", "group": 1 },
            { "name": "Sophie Stuckey", "group": 1 },
            { "name": "Casper Harvey", "group": 1 },
            { "name": "Eluned Jones", "group": 1 },
            { "name": "Gwenyth Petty", "group": 1 },
            { "name": "Robin Griffith", "group": 1 },
            { "name": "Bruce Willis", "group": 1 },
            { "name": "Gary Oldman", "group": 1 },
            { "name": "Ian Holm", "group": 1 },
            { "name": "Milla Jovovich", "group": 1 },
            { "name": "Chris Tucker", "group": 1 },
            { "name": "Luke Perry", "group": 1 },
            { "name": "Brion James", "group": 1 },
            { "name": "Tommy 'Tiny' Lister", "group": 1 },
            { "name": "Lee Evans", "group": 1 },
            { "name": "Charlie Creed-Miles", "group": 1 },
            { "name": "Tricky", "group": 1 },
            { "name": "John Neville", "group": 1 },
            { "name": "John Bluthal", "group": 1 },
            { "name": "Mathieu Kassovitz", "group": 1 },
            { "name": "Christopher Fairbank", "group": 1 },
            { "name": "Kim Chan", "group": 1 },
            { "name": "Julie T. Wallace", "group": 1 },
            { "name": "Al Matthews", "group": 1 },
            { "name": "Maïwenn", "group": 1 },
            { "name": "Mac McDonald", "group": 1 },
            { "name": "Indra Ové", "group": 1 },
            { "name": "Genevieve Maylam", "group": 1 },
            { "name": "Jason Salkey", "group": 1 },
            { "name": "Michael Culkin", "group": 1 },
            { "name": "Mark Hamill", "group": 1 },
            { "name": "Harrison Ford", "group": 1 },
            { "name": "Carrie Fisher", "group": 1 },
            { "name": "Peter Cushing", "group": 1 },
            { "name": "Alec Guinness", "group": 1 },
            { "name": "Anthony Daniels", "group": 1 },
            { "name": "Kenny Baker", "group": 1 },
            { "name": "Peter Mayhew", "group": 1 },
            { "name": "David Prowse", "group": 1 },
            { "name": "James Earl Jones", "group": 1 },
            { "name": "Phil Brown", "group": 1 },
            { "name": "Shelagh Fraser", "group": 1 },
            { "name": "Jack Purvis", "group": 1 },
            { "name": "Eddie Byrne", "group": 1 },
            { "name": "Denis Lawson", "group": 1 },
            { "name": "Garrick Hagon", "group": 1 },
            { "name": "Don Henderson", "group": 1 },
            { "name": "Leslie Schofield", "group": 1 },
            { "name": "Richard LeParmentier", "group": 1 },
            { "name": "Michael Leader", "group": 1 },
            { "name": "Alex McCrindle", "group": 1 },
            { "name": "Drewe Henley", "group": 1 },
            { "name": "Jack Klaff", "group": 1 },
            { "name": "William Hootkins", "group": 1 },
            { "name": "Angus MacInnes", "group": 1 },
            { "name": "Jeremy Sinden", "group": 1 },
            { "name": "Graham Ashley", "group": 1 },
            { "name": "David Ankrum", "group": 1 },
            { "name": "Mark Austin", "group": 1 },
            { "name": "Scott Beach", "group": 1 },
            { "name": "Lightning Bear", "group": 1 },
            { "name": "Jon Berg", "group": 1 },
            { "name": "Doug Beswick", "group": 1 },
            { "name": "Paul Blake", "group": 1 },
            { "name": "Janice Burchette", "group": 1 },
            { "name": "Ted Burnett", "group": 1 },
            { "name": "John Chapman", "group": 1 },
            { "name": "Gilda Cohen", "group": 1 },
            { "name": "Tim Condren", "group": 1 },
            { "name": "Barry Copping", "group": 1 },
            { "name": "Alfie Curtis", "group": 1 },
            { "name": "Robert Davies", "group": 1 },
            { "name": "Maria De Aragon", "group": 1 },
            { "name": "Robert A. Denham", "group": 1 },
            { "name": "Frazer Diamond", "group": 1 },
            { "name": "Peter Diamond", "group": 1 },
            { "name": "Warwick Diamond", "group": 1 },
            { "name": "Sadie Eden", "group": 1 },
            { "name": "Kim Falkinburg", "group": 1 },
            { "name": "Harry Fielder", "group": 1 },
            { "name": "Ted Gagliano", "group": 1 },
            { "name": "Salo Gardner", "group": 1 },
            { "name": "Steve Gawley", "group": 1 },
            { "name": "Barry Gnome", "group": 1 },
            { "name": "Rusty Goffe", "group": 1 },
            { "name": "Isaac Grand", "group": 1 },
            { "name": "Nelson Hall", "group": 1 },
            { "name": "Reg Harding", "group": 1 },
            { "name": "Alan Harris", "group": 1 },
            { "name": "Frank Henson", "group": 1 },
            { "name": "Christine Hewett", "group": 1 },
            { "name": "Arthur Howell", "group": 1 },
            { "name": "Tommy Ilsley", "group": 1 },
            { "name": "Joe Johnston", "group": 1 },
            { "name": "Annette Jones", "group": 1 },
            { "name": "Linda Jones", "group": 1 },
            { "name": "Joe Kaye", "group": 1 },
            { "name": "Colin Michael Kitchens", "group": 1 },
            { "name": "Melissa Kurtz", "group": 1 },
            { "name": "Tiffany L. Kurtz", "group": 1 },
            { "name": "Al Lampert", "group": 1 },
            { "name": "Anthony Lang", "group": 1 },
            { "name": "Laine Liska", "group": 1 },
            { "name": "Derek Lyons", "group": 1 },
            { "name": "Mahjoub", "group": 1 },
            { "name": "Alf Mangan", "group": 1 },
            { "name": "Rick McCallum", "group": 1 },
            { "name": "Grant McCune", "group": 1 },
            { "name": "Geoffrey Moon", "group": 1 },
            { "name": "Mandy Morton", "group": 1 },
            { "name": "Lorne Peterson", "group": 1 },
            { "name": "Marcus Powell", "group": 1 },
            { "name": "Shane Rimmer", "group": 1 },
            { "name": "Pam Rose", "group": 1 },
            { "name": "George Roubicek", "group": 1 },
            { "name": "Erica Simmons", "group": 1 },
            { "name": "Angela Staines", "group": 1 },
            { "name": "George Stock", "group": 1 },
            { "name": "Roy Straite", "group": 1 },
            { "name": "Peter Sturgeon", "group": 1 },
            { "name": "Peter Sumner", "group": 1 },
            { "name": "John Sylla", "group": 1 },
            { "name": "Tom Sylla", "group": 1 },
            { "name": "Malcolm Tierney", "group": 1 },
            { "name": "Phil Tippett", "group": 1 },
            { "name": "Burnell Tucker", "group": 1 },
            { "name": "Morgan Upton", "group": 1 },
            { "name": "Jerry Walter", "group": 1 },
            { "name": "Hal Wamsley", "group": 1 },
            { "name": "Larry Ward", "group": 1 },
            { "name": "Diana Sadley Way", "group": 1 },
            { "name": "Harold Weed", "group": 1 },
            { "name": "Bill Weston", "group": 1 },
            { "name": "Steve 'Spaz' Williams", "group": 1 },
            { "name": "Fred Wood", "group": 1 },
            { "name": "Colin Higgins", "group": 1 },
            { "name": "Orson Welles", "group": 1 },
            { "name": "Joseph Cotten", "group": 1 },
            { "name": "Dorothy Comingore", "group": 1 },
            { "name": "Ray Collins", "group": 1 },
            { "name": "George Coulouris", "group": 1 },
            { "name": "Agnes Moorehead", "group": 1 },
            { "name": "Paul Stewart", "group": 1 },
            { "name": "Ruth Warrick", "group": 1 },
            { "name": "Erskine Sanford", "group": 1 },
            { "name": "William Alland", "group": 1 },
            { "name": "Everett Sloane", "group": 1 },
            { "name": "Fortunio Bonanova", "group": 1 },
            { "name": "Gus Schilling", "group": 1 },
            { "name": "Philip Van Zandt", "group": 1 },
            { "name": "Georgia Backus", "group": 1 },
            { "name": "Harry Shannon", "group": 1 },
            { "name": "Sonny Bupp", "group": 1 },
            { "name": "Buddy Swan", "group": 1 },
            { "name": "Charles Bennett", "group": 1 },
            { "name": "Gregg Toland", "group": 1 },
            { "name": "Don Ackerman", "group": 1 },
            { "name": "Nat 'King' Cole", "group": 1 },
            { "name": "Gino Corrado", "group": 1 },
            { "name": "Maurice Costello", "group": 1 },
            { "name": "Demetrius Alexis", "group": 1 },
            { "name": "Gene Coogan", "group": 1 },
            { "name": "Art Dupuis", "group": 1 },
            { "name": "Rudy Germane", "group": 1 },
            { "name": "Mike Lally", "group": 1 },
            { "name": "Walter Lawrence", "group": 1 },
            { "name": "John Northpole", "group": 1 },
            { "name": "Victor Romito", "group": 1 },
            { "name": "Bob Terry", "group": 1 },
            { "name": "William Alston", "group": 1 },
            { "name": "Jack Gargan", "group": 1 },
            { "name": "Bert Moorhouse", "group": 1 },
            { "name": "Carmen Laroux", "group": 1 },
            { "name": "Sam Ash", "group": 1 },
            { "name": "Buddy Messinger", "group": 1 },
            { "name": "Terrance Ray", "group": 1 },
            { "name": "Sally Corner", "group": 1 },
            { "name": "Walter Bacon", "group": 1 },
            { "name": "Herbert Corthell", "group": 1 },
            { "name": "Harry A. Bailey", "group": 1 },
            { "name": "Danny Borzage", "group": 1 },
            { "name": "J.J. Clark", "group": 1 },
            { "name": "Tom Coleman", "group": 1 },
            { "name": "Carl Deloro", "group": 1 },
            { "name": "Jack Egan", "group": 1 },
            { "name": "Robert Haines", "group": 1 },
            { "name": "Ludwig Lowry", "group": 1 },
            { "name": "John McCormack", "group": 1 },
            { "name": "Hercules Mendez", "group": 1 },
            { "name": "Paddy O'Flynn", "group": 1 },
            { "name": "Sam Rice", "group": 1 },
            { "name": "Don Roberts", "group": 1 },
            { "name": "Larry Wheat", "group": 1 },
            { "name": "Larry Williams", "group": 1 },
            { "name": "Joan Blair", "group": 1 },
            { "name": "Morgan Brown", "group": 1 },
            { "name": "Harry Burkhardt", "group": 1 },
            { "name": "Edmund Cobb", "group": 1 },
            { "name": "Eddie Coke", "group": 1 },
            { "name": "Louis Natheaux", "group": 1 },
            { "name": "Arthur O'Connell", "group": 1 },
            { "name": "Guy Repp", "group": 1 },
            { "name": "Tom Steele", "group": 1 },
            { "name": "Richard Wilson", "group": 1 },
            { "name": "Louise Currie", "group": 1 },
            { "name": "Walter Sande", "group": 1 },
            { "name": "Jan Wiley", "group": 1 },
            { "name": "Milton Kibbee", "group": 1 },
            { "name": "Buck Mack", "group": 1 },
            { "name": "Alan Ladd", "group": 1 },
            { "name": "Thomas A. Curran", "group": 1 },
            { "name": "Jack Curtis", "group": 1 },
            { "name": "George Noisom", "group": 1 },
            { "name": "Gerald Pierce", "group": 1 },
            { "name": "Donna Dax", "group": 1 },
            { "name": "George DeNormand", "group": 1 },
            { "name": "Bud Geary", "group": 1 },
            { "name": "Bert LeBaron", "group": 1 },
            { "name": "Clyde McAtee", "group": 1 },
            { "name": "Cyril Ring", "group": 1 },
            { "name": "Roland Winters", "group": 1 },
            { "name": "Lew Harvey", "group": 1 },
            { "name": "Herman J. Mankiewicz", "group": 1 },
            { "name": "Eddie Dew", "group": 1 },
            { "name": "Perc Launders", "group": 1 },
            { "name": "John Dilson", "group": 1 },
            { "name": "Walter James", "group": 1 },
            { "name": "Robert Dudley", "group": 1 },
            { "name": "Suzanne Dulier", "group": 1 },
            { "name": "Al Eben", "group": 1 },
            { "name": "Johnny Eckert", "group": 1 },
            { "name": "Carl Ekberg", "group": 1 },
            { "name": "Edith Evanson", "group": 1 },
            { "name": "Carl Faulkner", "group": 1 },
            { "name": "Juanita Fields", "group": 1 },
            { "name": "Edna Mae Jones", "group": 1 },
            { "name": "Leda Nicova", "group": 1 },
            { "name": "Jolane Reynolds", "group": 1 },
            { "name": "Suzanne Ridgeway", "group": 1 },
            { "name": "Olin Francis", "group": 1 },
            { "name": "Louise Franklin", "group": 1 },
            { "name": "Renee Godfrey", "group": 1 },
            { "name": "Peter Gowland", "group": 1 },
            { "name": "Jimmy Grant", "group": 1 },
            { "name": "Jesse Graves", "group": 1 },
            { "name": "Ernest Grooney", "group": 1 },
            { "name": "Jack Gwynne", "group": 1 },
            { "name": "Teddy Mangean", "group": 1 },
            { "name": "Henry Hebert", "group": 1 },
            { "name": "Bryan 'Slim Hightower", "group": 1 },
            { "name": "Mitchell Ingraham", "group": 1 },
            { "name": "Philip Morris", "group": 1 },
            { "name": "Francis Sayles", "group": 1 },
            { "name": "George W. Jimenez", "group": 1 },
            { "name": "Arthur Kay", "group": 1 },
            { "name": "Ellen Lowe", "group": 1 },
            { "name": "James T. Mack", "group": 1 },
            { "name": "Mickey Martin", "group": 1 },
            { "name": "Bruce Sidney", "group": 1 },
            { "name": "Major McBride", "group": 1 },
            { "name": "Frank McLure", "group": 1 },
            { "name": "Charles Meakin", "group": 1 },
            { "name": "Edward Peil Jr.", "group": 1 },
            { "name": "Irving Mitchell", "group": 1 },
            { "name": "Frances E. Neal", "group": 1 },
            { "name": "Lillian Nicholson", "group": 1 },
            { "name": "Joseph North", "group": 1 },
            { "name": "William H. O'Brien", "group": 1 },
            { "name": "Field Norton", "group": 1 },
            { "name": "Dick Scott", "group": 1 },
            { "name": "Frank O'Connor", "group": 1 },
            { "name": "Russ Powell", "group": 1 },
            { "name": "Bert Stevens", "group": 1 },
            { "name": "Thomas Pogue", "group": 1 },
            { "name": "Lillian O'Malley", "group": 1 },
            { "name": "Jack Raymond", "group": 1 },
            { "name": "Gohr Van Vleck", "group": 1 },
            { "name": "Myrtle Rishell", "group": 1 },
            { "name": "Benny Rubin", "group": 1 },
            { "name": "Shimen Ruskin", "group": 1 },
            { "name": "George Sherwood", "group": 1 },
            { "name": "Edward Ryan", "group": 1 },
            { "name": "Landers Stevens", "group": 1 },
            { "name": "Harry J. Vejar", "group": 1 },
            { "name": "Tudor Williams", "group": 1 },
            { "name": "Arthur Yeoman", "group": 1 },
            { "name": "Tim Davis", "group": 1 },
            { "name": "Jamie Foxx", "group": 1 },
            { "name": "Jake Gyllenhaal", "group": 1 },
            { "name": "Scott MacDonald", "group": 1 },
            { "name": "Lucas Black", "group": 1 },
            { "name": "Peter Sarsgaard", "group": 1 },
            { "name": "Laz Alonso", "group": 1 },
            { "name": "Chris Cooper", "group": 1 },
            { "name": "Brian Geraghty", "group": 1 },
            { "name": "Damion Poitier", "group": 1 },
            { "name": "John Krasinski", "group": 1 },
            { "name": "Jocko Sims", "group": 1 },
            { "name": "Kevin Foster", "group": 1 },
            { "name": "Riad Galayini", "group": 1 },
            { "name": "Craig Coyne", "group": 1 },
            { "name": "Katherine Randolph", "group": 1 },
            { "name": "Honorine Bell", "group": 1 },
            { "name": "Dendrie Taylor", "group": 1 },
            { "name": "James Morrison", "group": 1 },
            { "name": "Ming Lo", "group": 1 },
            { "name": "Dennis Haysbert", "group": 1 },
            { "name": "Michael Hynson", "group": 1 },
            { "name": "Robert August", "group": 1 },
            { "name": "Lord 'Tally Ho' Blears", "group": 1 },
            { "name": "Bruce Brown", "group": 1 },
            { "name": "Chip Fitzwater", "group": 1 },
            { "name": "Chuck Gardner", "group": 1 },
            { "name": "Wayne Miyata", "group": 1 },
            { "name": "Johnny Depp", "group": 1 },
            { "name": "Geoffrey Rush", "group": 1 },
            { "name": "Orlando Bloom", "group": 1 },
            { "name": "Keira Knightley", "group": 1 },
            { "name": "Jack Davenport", "group": 1 },
            { "name": "Jonathan Pryce", "group": 1 },
            { "name": "Kevin McNally", "group": 1 },
            { "name": "Zoe Saldana", "group": 1 },
            { "name": "Lee Arenberg", "group": 1 },
            { "name": "Mackenzie Crook", "group": 1 },
            { "name": "Damian O'Hare", "group": 1 },
            { "name": "Giles New", "group": 1 },
            { "name": "Angus Barnett", "group": 1 },
            { "name": "David Bailie", "group": 1 },
            { "name": "Martin Klebba", "group": 1 },
            { "name": "Treva Etienne", "group": 1 },
            { "name": "Michael Berry Jr.", "group": 1 },
            { "name": "Isaac C. Singleton Jr.", "group": 1 },
            { "name": "Greg Ellis", "group": 1 },
            { "name": "Guy Siner", "group": 1 },
            { "name": "Ralph P. Martin", "group": 1 },
            { "name": "Paula J. Newman", "group": 1 },
            { "name": "Paul Keith", "group": 1 },
            { "name": "Dylan Smith", "group": 1 },
            { "name": "Lucinda Dryzek", "group": 1 },
            { "name": "Lauren Maher", "group": 1 },
            { "name": "Vanessa Branch", "group": 1 },
            { "name": "Luke de Woolfson", "group": 1 },
            { "name": "Michael Sean Tighe", "group": 1 },
            { "name": "Dustin Seavey", "group": 1 },
            { "name": "Christian Martin", "group": 1 },
            { "name": "Trevor Goddard", "group": 1 },
            { "name": "Vince Lozano", "group": 1 },
            { "name": "Matthew Bowyer", "group": 1 },
            { "name": "Brye Cooper", "group": 1 },
            { "name": "Ben Wilson", "group": 1 },
            { "name": "Antonio Valentino", "group": 1 },
            { "name": "Mike Babcock", "group": 1 },
            { "name": "Owen Finnegan", "group": 1 },
            { "name": "Ian McIntyre", "group": 1 },
            { "name": "Israel Aduramo", "group": 1 },
            { "name": "Sam Roberts", "group": 1 },
            { "name": "Ben Roberts", "group": 1 },
            { "name": "Félix Castro", "group": 1 },
            { "name": "Mike Haberecht", "group": 1 },
            { "name": "Rudolph McCollum", "group": 1 },
            { "name": "Gerard J. Reyes", "group": 1 },
            { "name": "M. Scott Shields", "group": 1 },
            { "name": "Christopher Sullivan", "group": 1 },
            { "name": "Craig Thomson", "group": 1 },
            { "name": "Fred Toft", "group": 1 },
            { "name": "Jerry Gauny", "group": 1 },
            { "name": "Maxie J. Santillan Jr.", "group": 1 },
            { "name": "Michael Earl Lane", "group": 1 },
            { "name": "David Patykewich", "group": 1 },
            { "name": "Tommy Schooler", "group": 1 },
            { "name": "Finneus Egan", "group": 1 },
            { "name": "D.P. FitzGerald", "group": 1 },
            { "name": "Tobias McKinney", "group": 1 },
            { "name": "Michael A. Thompson", "group": 1 },
            { "name": "Michael W. Williams", "group": 1 },
            { "name": "Jose Zelaya", "group": 1 },
            { "name": "Don LaDaga", "group": 1 },
            { "name": "LeJon", "group": 1 },
            { "name": "Christopher S. Capp", "group": 1 },
            { "name": "Gregory Alosio", "group": 1 },
            { "name": "Jordi Caballero", "group": 1 },
            { "name": "Paul Gagné", "group": 1 },
            { "name": "Joe Grisaffi", "group": 1 },
            { "name": "James McAuley", "group": 1 },
            { "name": "Uma Thurman", "group": 1 },
            { "name": "Lucy Liu", "group": 1 },
            { "name": "Vivica A. Fox", "group": 1 },
            { "name": "Daryl Hannah", "group": 1 },
            { "name": "David Carradine", "group": 1 },
            { "name": "Michael Madsen", "group": 1 },
            { "name": "Julie Dreyfus", "group": 1 },
            { "name": "Chiaki Kuriyama", "group": 1 },
            { "name": "Sonny Chiba", "group": 1 },
            { "name": "Gordon Liu Chia-Hui", "group": 1 },
            { "name": "Michael Parks", "group": 1 },
            { "name": "Michael Bowen", "group": 1 },
            { "name": "Jun Kunimura", "group": 1 },
            { "name": "Kenji Ohba", "group": 1 },
            { "name": "Yuki Kazamatsuri", "group": 1 },
            { "name": "James Parks", "group": 1 },
            { "name": "Sakichi Satô", "group": 1 },
            { "name": "Jonathan Loughran", "group": 1 },
            { "name": "Yoshiyuki Morishita", "group": 1 },
            { "name": "Tetsuro Shimaguchi", "group": 1 },
            { "name": "Kazuki Kitamura", "group": 1 },
            { "name": "Yôji Tanaka", "group": 1 },
            { "name": "Issei Takahashi", "group": 1 },
            { "name": "Sô Yamanaka", "group": 1 },
            { "name": "Julie Manase", "group": 1 },
            { "name": "Akaji Maro", "group": 1 },
            { "name": "Goro Daimon", "group": 1 },
            { "name": "Shun Sugata", "group": 1 },
            { "name": "Zhang Jin Zhan", "group": 1 },
            { "name": "Hu Xiaohui", "group": 1 },
            { "name": "Ambrosia Kelley", "group": 1 },
            { "name": "Sachiko Fujii", "group": 1 },
            { "name": "Shu Lan Tuan", "group": 1 },
            { "name": "Ai Maeda", "group": 1 },
            { "name": "Naomi Kusumi", "group": 1 },
            { "name": "Hikaru Midorikawa", "group": 1 },
            { "name": "Hisao Egawa", "group": 1 },
            { "name": "Nobuaki Fukuda", "group": 1 },
            { "name": "Yu Hayashi", "group": 1 },
            { "name": "Hiroaki Ishikawa", "group": 1 },
            { "name": "Yoshio Kawai", "group": 1 },
            { "name": "Takurô Kitagawa", "group": 1 },
            { "name": "Atsuko Mine", "group": 1 },
            { "name": "Takashi Nagasako", "group": 1 },
            { "name": "Ryûji Nakagi", "group": 1 },
            { "name": "Hidetoshi Nakamura", "group": 1 },
            { "name": "Youko Otomo", "group": 1 },
            { "name": "Ai Satô", "group": 1 },
            { "name": "Masaharu Satô", "group": 1 },
            { "name": "Kôzô Shioya", "group": 1 },
            { "name": "Keiichi Sonobe", "group": 1 },
            { "name": "Katsumi Suzuki", "group": 1 },
            { "name": "Kazumi Tanaka", "group": 1 },
            { "name": "Seiko Tomoe", "group": 1 },
            { "name": "Keaton Yamada", "group": 1 },
            { "name": "Keiko Yamamoto", "group": 1 },
            { "name": "Lior Ashkenazi", "group": 1 },
            { "name": "Knut Berger", "group": 1 },
            { "name": "Caroline Peters", "group": 1 },
            { "name": "Gideon Shemer", "group": 1 },
            { "name": "Carola Regnier", "group": 1 },
            { "name": "Hanns Zischler", "group": 1 },
            { "name": "Ernest Lenart", "group": 1 },
            { "name": "Kieran O'Brien", "group": 1 },
            { "name": "Margo Stilley", "group": 1 },
            { "name": "Courtney Taylor-Taylor", "group": 1 },
            { "name": "Alex Kapranos", "group": 1 },
            { "name": "Guy Garvey", "group": 1 },
            { "name": "Robert Levon Been", "group": 1 },
            { "name": "Peter Hayes", "group": 1 },
            { "name": "Gruff Rhys", "group": 1 },
            { "name": "Jason Stollsteimer", "group": 1 },
            { "name": "Marcie Bolen", "group": 1 },
            { "name": "Michael Nyman", "group": 1 },
            { "name": "Bobby Gillespie", "group": 1 },
            { "name": "Dan Castellaneta", "group": 1 },
            { "name": "Julie Kavner", "group": 1 },
            { "name": "Nancy Cartwright", "group": 1 },
            { "name": "Yeardley Smith", "group": 1 },
            { "name": "Hank Azaria", "group": 1 },
            { "name": "Harry Shearer", "group": 1 },
            { "name": "Kelsey Grammer", "group": 1 },
            { "name": "Maile Flanagan", "group": 1 },
            { "name": "Pamela Hayden", "group": 1 },
            { "name": "Marcia Wallace", "group": 1 },
            { "name": "Joe Mantegna", "group": 1 },
            { "name": "Tom Hanks", "group": 1 },
            { "name": "Billie Joe Armstrong", "group": 1 },
            { "name": "Mike Dirnt", "group": 1 },
            { "name": "Tre Cool", "group": 1 },
            { "name": "Tress MacNeille", "group": 1 },
            { "name": "Albert Brooks", "group": 1 },
            { "name": "Russi Taylor", "group": 1 },
            { "name": "Karl Wiedergott", "group": 1 },
            { "name": "Maggie Roswell", "group": 1 },
            { "name": "Philip Rosenthal", "group": 1 },
            { "name": "Jim Carrey", "group": 1 },
            { "name": "Kate Winslet", "group": 1 },
            { "name": "Elijah Wood", "group": 1 },
            { "name": "Mark Ruffalo", "group": 1 },
            { "name": "Kirsten Dunst", "group": 1 },
            { "name": "Tom Wilkinson", "group": 1 },
            { "name": "Ryan Whitney", "group": 1 },
            { "name": "Jane Adams", "group": 1 },
            { "name": "Debbon Ayer", "group": 1 },
            { "name": "David Cross", "group": 1 },
            { "name": "Gerry Robert Byrne", "group": 1 },
            { "name": "Brian Price", "group": 1 },
            { "name": "Josh Flitter", "group": 1 },
            { "name": "Paul Litowsky", "group": 1 },
            { "name": "Lola Daehler", "group": 1 },
            { "name": "Amir Ali Said", "group": 1 },
            { "name": "Deirdre O'Connell", "group": 1 },
            { "name": "Lauren Adler", "group": 1 },
            { "name": "Tsutomu Isobe", "group": 1 },
            { "name": "Ami Hasegawa", "group": 1 },
            { "name": "Gara Takashima", "group": 1 },
            { "name": "Kouichi Yamadera", "group": 1 },
            { "name": "Clint Eastwood", "group": 1 },
            { "name": "Gene Hackman", "group": 1 },
            { "name": "Morgan Freeman", "group": 1 },
            { "name": "Richard Harris", "group": 1 },
            { "name": "Jaimz Woolvett", "group": 1 },
            { "name": "Anna Levine", "group": 1 },
            { "name": "Saul Rubinek", "group": 1 },
            { "name": "Frances Fisher", "group": 1 },
            { "name": "David Mucci", "group": 1 },
            { "name": "Rob Campbell", "group": 1 },
            { "name": "Anthony James", "group": 1 },
            { "name": "Ron White", "group": 1 },
            { "name": "Jefferson Mappin", "group": 1 },
            { "name": "Jeremy Ratchford", "group": 1 },
            { "name": "Philip Maurice Hayes", "group": 1 },
            { "name": "Tara Frederick", "group": 1 },
            { "name": "Beverley Elliott", "group": 1 },
            { "name": "Liisa Repo-Martell", "group": 1 },
            { "name": "Shane Meier", "group": 1 },
            { "name": "Robert Koons", "group": 1 },
            { "name": "Mina E. Mina", "group": 1 },
            { "name": "John Pyper-Ferguson", "group": 1 },
            { "name": "Walter Marsh", "group": 1 },
            { "name": "Larry Reese", "group": 1 },
            { "name": "Blair Haynes", "group": 1 },
            { "name": "Frank C. Turner", "group": 1 },
            { "name": "Lochlyn Munro", "group": 1 },
            { "name": "Ben Cardinal", "group": 1 },
            { "name": "Michael Charrois", "group": 1 },
            { "name": "Michael Maurer", "group": 1 },
            { "name": "Larry Joshua", "group": 1 },
            { "name": "George Orrison", "group": 1 },
            { "name": "Greg Goossen", "group": 1 },
            { "name": "Martin Sheen", "group": 1 },
            { "name": "Marlon Brando", "group": 1 },
            { "name": "Robert Duvall", "group": 1 },
            { "name": "Laurence Fishburne", "group": 1 },
            { "name": "Sam Bottoms", "group": 1 },
            { "name": "Frederic Forrest", "group": 1 },
            { "name": "Albert Hall", "group": 1 },
            { "name": "Harrison Ford", "group": 1 },
            { "name": "Dennis Hopper", "group": 1 },
            { "name": "G. D. Spradlin", "group": 1 },
            { "name": "Jerry Ziesmer", "group": 1 },
            { "name": "Tom Mason", "group": 1 },
            { "name": "Scott Glenn", "group": 1 },
            { "name": "James Keane", "group": 1 },
            { "name": "Kerry Rossall", "group": 1 },
            { "name": "Colleen Camp", "group": 1 },
            { "name": "Cynthia Wood", "group": 1 },
            { "name": "Linda Carpenter", "group": 1 },
            { "name": "Jack Thibeau", "group": 1 },
            { "name": "Damien Leake", "group": 1 },
            { "name": "Marc Coppola", "group": 1 },
            { "name": "Glenn Walken", "group": 1 },
            { "name": "Bill Graham", "group": 1 },
            { "name": "Jerry Ross", "group": 1 },
            { "name": "Charles Robinson", "group": 1 },
            { "name": "Nick Nicholson", "group": 1 },
            { "name": "Don Gordon Bell", "group": 1 },
            { "name": "Evan A. Lottman", "group": 1 },
            { "name": "R. Lee Ermey", "group": 1 },
            { "name": "Jim Gaines", "group": 1 },
            { "name": "Charlie Sheen", "group": 1 },
            { "name": "Vittorio Storaro", "group": 1 },
            { "name": "Francis Ford Coppola", "group": 1 },
            { "name": "Henry Strzalkowski", "group": 1 },
            { "name": "Lonnie Woodley", "group": 1 },
            { "name": "Johnny Depp", "group": 1 },
            { "name": "Orlando Bloom", "group": 1 },
            { "name": "Keira Knightley", "group": 1 },
            { "name": "Bill Nighy", "group": 1 },
            { "name": "Jack Davenport", "group": 1 },
            { "name": "Stellan Skarsgård", "group": 1 },
            { "name": "Kevin McNally", "group": 1 },
            { "name": "Jonathan Pryce", "group": 1 },
            { "name": "Lee Arenberg", "group": 1 },
            { "name": "Mackenzie Crook", "group": 1 },
            { "name": "Tom Hollander", "group": 1 },
            { "name": "Naomie Harris", "group": 1 },
            { "name": "David Bailie", "group": 1 },
            { "name": "Martin Klebba", "group": 1 },
            { "name": "David Schofield", "group": 1 },
            { "name": "Alex Norton", "group": 1 },
            { "name": "Geoffrey Rush", "group": 1 },
            { "name": "Lauren Maher", "group": 1 },
            { "name": "Vanessa Branch", "group": 1 },
            { "name": "Luke de Woolfson", "group": 1 },
            { "name": "Jonathan Kite", "group": 1 },
            { "name": "Ho-Kwan Tse", "group": 1 },
            { "name": "Peter Donald Badalamenti II", "group": 1 },
            { "name": "Christopher S. Capp", "group": 1 },
            { "name": "Max Baker", "group": 1 },
            { "name": "Steve Speirs", "group": 1 },
            { "name": "Reggie Lee", "group": 1 },
            { "name": "Gael García Bernal", "group": 1 },
            { "name": "Vanessa Bauche", "group": 1 },
            { "name": "Goya Toledo", "group": 1 },
            { "name": "Alvaro Guerrero", "group": 1 },
            { "name": "Emilio Echevarría", "group": 1 },
            { "name": "Jorge Salinas", "group": 1 },
            { "name": "Rodrigo Murray", "group": 1 },
            { "name": "Humberto Busto", "group": 1 },
            { "name": "Gerardo Campbell", "group": 1 },
            { "name": "Rosa María Bianchi", "group": 1 },
            { "name": "Dunia Saldívar", "group": 1 },
            { "name": "Adriana Barraza", "group": 1 },
            { "name": "José Sefami", "group": 1 },
            { "name": "Lourdes Echevarría", "group": 1 },
            { "name": "Marco Pérez", "group": 1 },
            { "name": "Laura Almela", "group": 1 },
            { "name": "Gustavo Sánchez Parra", "group": 1 },
            { "name": "Dagoberto Gama", "group": 1 },
            { "name": "Rodrigo Ostap", "group": 1 },
            { "name": "Patricio Castillo", "group": 1 },
            { "name": "Roberto Medina", "group": 1 },
            { "name": "Carlos Samperio", "group": 1 },
            { "name": "Mauricio Martínez", "group": 1 },
            { "name": "Ricardo Dalmacci", "group": 1 },
            { "name": "Gustavo Muñoz", "group": 1 },
            { "name": "Viggo Mortensen", "group": 1 },
            { "name": "Maria Bello", "group": 1 },
            { "name": "Heidi Hayes", "group": 1 },
            { "name": "Ashton Holmes", "group": 1 },
            { "name": "William Hurt", "group": 1 },
            { "name": "Ed Harris", "group": 1 },
            { "name": "Peter MacNeill", "group": 1 },
            { "name": "Stephen McHattie", "group": 1 },
            { "name": "Greg Bryk", "group": 1 },
            { "name": "Kyle Schmid", "group": 1 },
            { "name": "Sumela Kay", "group": 1 },
            { "name": "Gerry Quigley", "group": 1 },
            { "name": "Deborah Drakeford", "group": 1 },
            { "name": "Bill MacDonald", "group": 1 },
            { "name": "Aidan Devine", "group": 1 }

        ]

var obj = {};
obj.nodes = [];
obj.links = [];

function parseNode(){
    for(var i in data){
        for(var a in data[i].cast){
            var src = data[i].cast[a];
            if(containsNode(src, obj.nodes) != null){
                var nodeObj = {};
                nodeObj.name = src;
                nodeObj.group = 1;
                //console.log(nodeObj);
                //obj.nodes.push(nodeObj);
                }
        }
    }
}

function parseLinks(){
    for(var i in data){
        for(var a in data[i].cast){
            var src = data[i].cast[a];
            var srcNum = containsNode(src, people);
            if(srcNum != null){
                for(var b in data[i].cast){
                    var destNum = containsNode(data[i].cast[b],people);
                    if(destNum != null){
                        var linkObj = {};
                        linkObj.source = srcNum;
                        linkObj.target = destNum;
                        linkObj.value = 1;
                        //console.log(linkObj);
                        obj.links.push(linkObj);
                    }
                }
            }
        }
    }
}
parseLinks();
console.log(obj.links);

function containsNode(name, arr){
    for(var i =0;i<arr.length; i++){
        if(arr[i].name == name){
            //console.log(i);
            return i;
        }
    }
    return null;
}
